version: '2'
services:
  plex:
    container_name: noordflix
    image: plexinc/pms-docker
    network_mode: host
    restart: always
    environment:
      - TZ=Africa\Johannesburg
      - PLEX_CLAIM=7i81Cm-TzyoSPF9rrtcg
    volumes:
      - /plex:/config
      - /plex:/transcode
      - /plex:/media
