version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    network_mode: host
    restart: always
    environment:
      - TZ=Africa\Johannesburg
      - PLEX_CLAIM=7i81Cm-TzyoSPF9rrtcg
    volumes:
      - /mnt/120GB:/plex/config
      - /mnt/120GB:/plex/transcode
      - /mnt/120GB:/plex/media